### ISSUE TITLE
Dimensions Entity

### ISSUE THREAD

**Issue by philip-very** [mozman/dxfgrabber#14]
Hello, 

I'm trying to get Information out of a DIMENSION-entity. Unfortunately, this entity-type is not
supported, although thr block, in which the dimension is displayed is included.
Is there a way to include the DIMENSION-entities besides only using the entry from the block-section?

Kind regards

**Comment by mozman** [comment]
Hi,
because I don't want to maintain multiple DXF related packages, dxfgrabber will not get any new features. But my ezdxf package has read support for DIMENSION and some time may be write support, unfortunately ezdxf has a complete different API, but ezdxf is more powerful and more important, it is my only DXF package that gets new features, espacially if someone ask for it.
